#!/usr/bin/env bash
# sync-upstream.sh — fetch an upstream remote and merge it into this fork via a
# review-friendly pull request.
#
# This repo is a deliberately-diverging fork, so every upstream sync is a
# candidate for conflicts. Rather than merging straight into your base branch,
# this script merges onto an isolated `sync-upstream-<date>` branch and opens a
# PR, so nothing lands on your base until you review it.
#
# Usage:
#   ./tools/sync-upstream.sh [options]
#   ./tools/sync-upstream.sh --continue [options]   # resume after resolving conflicts
#
# Options:
#   --remote <name>          upstream remote to merge from (default: upstream)
#   --upstream-branch <name> branch on that remote to merge (default: main)
#   --base <branch>          branch to fork from and target the PR at (default: main)
#   --draft                  open the PR as a draft
#   --dry-run                fetch and show the incoming commit range, then stop
#   --force, -f              overwrite an existing sync branch of the same name
#   --skip-readonly-check    skip the read-only-file pre-flight (e.g. on the host)
#   --continue               finalize a conflict-resolved merge, push, open the PR
#   -h, --help               show this help
#
# Read-only mounts: several paths (.devcontainer/**, .vscode/tasks.json,
# ~/.gitconfig, ...) are bind-mounted read-only from the host inside the dev
# container. If an incoming merge would touch one of those, the pre-flight check
# stops and tells you to re-run this script from the host, where /workspace is
# writable. See CLAUDE.md → "Read-only mounts".
set -euo pipefail

usage() {
    # Print only the leading comment block (skip the shebang, stop at the first
    # non-comment line, e.g. `set -euo pipefail`) so section comments below
    # don't leak into --help.
    sed -n '2,/^[^#]/p' "$0" | sed -e 's/^# \{0,1\}//' -e '/^set /d'
    exit 1
}

# ── Defaults ────────────────────────────────────────────────────────────────
REMOTE="upstream"
UPSTREAM_BRANCH="main"
BASE="main"
DRAFT=0
DRY_RUN=0
FORCE=0
SKIP_RO_CHECK=0
CONTINUE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote) REMOTE="$2"; shift 2 ;;
        --upstream-branch) UPSTREAM_BRANCH="$2"; shift 2 ;;
        --base) BASE="$2"; shift 2 ;;
        --draft) DRAFT=1; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        --force|-f) FORCE=1; shift ;;
        --skip-readonly-check) SKIP_RO_CHECK=1; shift ;;
        --continue) CONTINUE=1; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
done

die() { echo "Error: $*" >&2; exit 1; }

# ── Shared helpers ────────────────────────────────────────────────────────────

# Derive "owner/repo" from a remote URL (handles https and ssh forms).
remote_repo_name() {
    local url
    url="$(git remote get-url "$REMOTE")"
    url="${url%.git}"
    url="${url#*github.com/}"
    url="${url#*github.com:}"
    echo "$url"
}

require_gh() {
    command -v gh >/dev/null 2>&1 || die "the 'gh' CLI is required to open the PR"
    gh auth status >/dev/null 2>&1 || die "run 'gh auth login' first"
}

# Push the current sync branch and open the PR. Used by both the clean-merge
# path and --continue, so PR creation lives in exactly one place.
push_and_open_pr() {
    local branch repo range title body
    branch="$(git rev-parse --abbrev-ref HEAD)"
    repo="$(remote_repo_name)"
    range="$(git log --oneline "${BASE}..${REMOTE}/${UPSTREAM_BRANCH}" 2>/dev/null || true)"

    echo "Pushing $branch to origin..."
    git push --set-upstream origin "$branch"

    title="Sync upstream (${repo}) — ${SYNC_DATE}"
    body="$(cat <<EOF
Merges \`${REMOTE}/${UPSTREAM_BRANCH}\` (${repo}) into \`${BASE}\`.

Incoming commits:

\`\`\`
${range:-（range unavailable）}
\`\`\`

Generated by \`tools/sync-upstream.sh\`.
EOF
)"

    local draft_flag=()
    [[ "$DRAFT" -eq 1 ]] && draft_flag=(--draft)

    echo "Opening PR against $BASE..."
    require_gh
    gh pr create --base "$BASE" --head "$branch" \
        --title "$title" --body "$body" "${draft_flag[@]}"
}

# ── --continue: finalize a conflict-resolved merge ────────────────────────────
if [[ "$CONTINUE" -eq 1 ]]; then
    branch="$(git rev-parse --abbrev-ref HEAD)"
    case "$branch" in
        sync-upstream-*) ;;
        *) die "--continue must be run from a sync-upstream-* branch (you are on '$branch')" ;;
    esac
    # Recover the sync date from the branch name so the PR title matches.
    SYNC_DATE="${branch#sync-upstream-}"

    if [[ -f "$(git rev-parse --git-dir)/MERGE_HEAD" ]]; then
        # Merge still in progress — make sure nothing is left unresolved.
        if git diff --name-only --diff-filter=U | grep -q .; then
            echo "Still-unresolved paths:" >&2
            git diff --name-only --diff-filter=U | sed 's/^/  /' >&2
            die "resolve the conflicts and 'git add' them before --continue"
        fi
        echo "Finalizing merge commit..."
        git commit --no-edit
    else
        echo "No merge in progress; assuming the merge commit already exists."
    fi

    push_and_open_pr
    echo "Done."
    exit 0
fi

# ── Preconditions ─────────────────────────────────────────────────────────────
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"

git remote get-url "$REMOTE" >/dev/null 2>&1 \
    || die "remote '$REMOTE' is not configured (add it with: git remote add $REMOTE <url>)"

[[ -z "$(git status --porcelain)" ]] \
    || die "working tree is not clean; commit or stash your changes first"

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[[ "$CURRENT_BRANCH" == "$BASE" ]] \
    || die "must be on '$BASE' to start a sync (you are on '$CURRENT_BRANCH')"

# ── Fetch ─────────────────────────────────────────────────────────────────────
echo "Fetching $REMOTE/$UPSTREAM_BRANCH..."
if ! git fetch "$REMOTE" "$UPSTREAM_BRANCH"; then
    cat >&2 <<EOF

Error: failed to fetch $REMOTE/$UPSTREAM_BRANCH.

If this is a network block, it is most likely the firewall allowlist, not a
DNS/connectivity/URL problem. Check recent denials:

    curl -s http://firewall:8099

Then, from the HOST, allow the upstream host (e.g. github.com):

    docker exec <firewall-container> fw allow github.com

(A process inside the container cannot modify its own allowlist, by design.)
EOF
    exit 1
fi

# ── Up-to-date check ──────────────────────────────────────────────────────────
INCOMING_COUNT="$(git rev-list --count "${BASE}..${REMOTE}/${UPSTREAM_BRANCH}")"
if [[ "$INCOMING_COUNT" -eq 0 ]]; then
    echo "Already up to date with $REMOTE/$UPSTREAM_BRANCH — nothing to sync."
    exit 0
fi
echo "$INCOMING_COUNT incoming commit(s) from $REMOTE/$UPSTREAM_BRANCH."

# ── Dry-run ───────────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" -eq 1 ]]; then
    echo
    echo "Incoming commits (${BASE}..${REMOTE}/${UPSTREAM_BRANCH}):"
    git log --oneline "${BASE}..${REMOTE}/${UPSTREAM_BRANCH}"
    echo
    echo "(dry run — no branch created, no merge performed)"
    exit 0
fi

# ── Read-only pre-flight ──────────────────────────────────────────────────────
# An upstream merge can touch files that are bind-mounted read-only from the
# host (see CLAUDE.md). Merging those from inside the container fails partway.
# Probe writability of every incoming path *before* touching anything.
if [[ "$SKIP_RO_CHECK" -eq 0 ]]; then
    readonly_hits=()
    while IFS= read -r path; do
        [[ -z "$path" ]] && continue
        if [[ -e "$path" ]]; then
            # Existing file: can we open it for writing without changing it?
            if ! ( exec 3>>"$path" ) 2>/dev/null; then
                readonly_hits+=("$path")
            fi
        else
            # New file: is its nearest existing parent directory writable?
            dir="$(dirname "$path")"
            while [[ ! -e "$dir" && "$dir" != "." && "$dir" != "/" ]]; do
                dir="$(dirname "$dir")"
            done
            if ! ( probe="$dir/.sync-upstream-wtest.$$"; touch "$probe" ) 2>/dev/null; then
                readonly_hits+=("$path")
            else
                rm -f "$dir/.sync-upstream-wtest.$$" 2>/dev/null || true
            fi
        fi
    done < <(git diff --name-only "${BASE}..${REMOTE}/${UPSTREAM_BRANCH}")

    if [[ ${#readonly_hits[@]} -gt 0 ]]; then
        {
            echo
            echo "Error: the incoming merge would modify files that are read-only"
            echo "inside this container:"
            printf '  %s\n' "${readonly_hits[@]}"
            echo
            echo "These are bind-mounted read-only from the host. Re-run this script"
            echo "from the HOST, where /workspace is writable:"
            echo
            echo "    ./tools/sync-upstream.sh $*"
            echo
            echo "(or bypass this check with --skip-readonly-check if you know better)."
        } >&2
        exit 1
    fi
fi

# ── Create sync branch ────────────────────────────────────────────────────────
SYNC_DATE="$(date -u +%Y%m%d)"
SYNC_BRANCH="sync-upstream-${SYNC_DATE}"

if git show-ref --verify --quiet "refs/heads/${SYNC_BRANCH}"; then
    if [[ "$FORCE" -eq 1 ]]; then
        echo "Overwriting existing branch $SYNC_BRANCH (--force)..."
        git branch -D "$SYNC_BRANCH"
    else
        die "branch '$SYNC_BRANCH' already exists (use --force to overwrite)"
    fi
fi

echo "Creating $SYNC_BRANCH from $BASE..."
git checkout -b "$SYNC_BRANCH" "$BASE"

# ── Merge ─────────────────────────────────────────────────────────────────────
REPO_NAME="$(remote_repo_name)"
MERGE_MSG="Merge ${REMOTE}/${UPSTREAM_BRANCH} (${REPO_NAME}) into ${BASE}

Syncs ${INCOMING_COUNT} upstream commit(s) via tools/sync-upstream.sh."

echo "Merging $REMOTE/$UPSTREAM_BRANCH (--no-ff)..."
if ! git merge --no-ff -m "$MERGE_MSG" "${REMOTE}/${UPSTREAM_BRANCH}"; then
    {
        echo
        echo "Merge stopped with conflicts in:"
        git diff --name-only --diff-filter=U | sed 's/^/  /'
        echo
        echo "Resolve them, then:"
        echo "  git add <files>"
        echo "  ./tools/sync-upstream.sh --continue     # finalizes the merge, pushes, opens the PR"
        echo
        echo "Or abort entirely:"
        echo "  git merge --abort"
        echo "  git checkout $BASE && git branch -D $SYNC_BRANCH"
    } >&2
    exit 1
fi

# ── Push + PR ─────────────────────────────────────────────────────────────────
push_and_open_pr
echo "Done."
